import copy
from .models import DIMENSIONS, Discovery
from .policy import evaluate
from .store import now

def sample_payload():
    date = now()[:10]
    sources = [
        dict(id="S1",url="https://example.com/fictional/alex", title="Example operator account A", published_at=date,retrieved_at=date,kind="firsthand",speaker="Example Alex",organization="Example North",origin_url=None,excerpt="I manually verify the same exceptions every week.",supports="Illustrative recurring workflow and time cost. This is fictional.",accessed=True),
        dict(id="S2",url="https://example.org/fictional/river", title="Example operator account B", published_at=date,retrieved_at=date,kind="firsthand",speaker="Example River",organization="Example South",origin_url=None,excerpt="Our team pays for manual checking and still misses changes.",supports="Illustrative independent complaint and paid workaround. This is fictional.",accessed=True),
        dict(id="S3",url="https://example.net/fictional/vendor",title="Example product documentation",published_at=date,retrieved_at=date,kind="documentation",speaker=None,organization="Example Vendor",origin_url=None,excerpt="Exports are available; reviewing exceptions is a manual task.",supports="Illustrative integration feasibility. This is fictional.",accessed=True)
    ]
    pain = dict(id="P1",title="Manual checks before sharing AI-generated metrics",customer="Small analytics teams",buyer="Analytics engineering lead",workflow="Reviewing generated metric reports before sending them to customers",problem="The team repeatedly checks definitions and source changes by hand.",frequency="Illustration: weekly, with extra checks after releases.",consequence="Illustration: several hours of review and delayed customer reporting.",workaround="Manual SQL checks and a spreadsheet of exceptions.",spending_evidence="Fictional operator reports paid manual checking; no actual willingness to pay is established.",source_ids=["S1","S2"],consequence_source_ids=["S1"],uncertainties=["All evidence in this example is synthetic."])
    values = [4,4,3,3,3,4,4,3,2]
    scores = [dict(dimension=k,value=values[i],confidence="medium" if i < 3 else "low",rationale="Illustrative assessment supported by fictional evidence; not a market conclusion.",source_ids=["S1","S2"] if i<3 else ["S3"],assumptions=["A narrow integration is enough for a useful first version."],counterevidence="The existing platform might add these checks.",next_evidence="Interview three buyers and inspect their real review workflow.") for i,k in enumerate(DIMENSIONS)]
    opportunity = dict(id="O1",pain_id="P1",title="A release check for AI-generated metrics",thesis="Illustration: make recurring metric checks repeatable for a small data team.",solution="A narrow checker that replays approved questions against a stable dataset and flags changes.",why_now="Illustration: teams are starting to share agent-generated reports.",why_now_source_ids=["S3"],buyer="Analytics engineering lead",status="worth_validating",ranking_reason="Example of strong pain with weaker defensibility; compare dimensions rather than a blended score.",founder_fit="Potentially suitable for a software founder. Skills and customer access are unknown.",scores=scores,competitors=[dict(name="Existing analytics platform",offering="Built-in reporting and some tests.",price_evidence="Unknown — fictional example.",gap="Requires verification with a real buyer.",source_ids=["S3"])],mvp="One data source, approved examples, and a before/after report.",build_effort="Illustrative estimate: several weeks; must be scoped.",upfront_cost="Unknown; evaluate case by case.",monthly_cost="Depends on query and model usage.",support_burden="Investigate integration maintenance and false positives.",sales_effort="Test direct outreach through data communities.",time_to_pilot="Unknown until a design partner agrees.",dependencies=["Customer-authorized sample data"],solo_blockers=[],constraint_conflicts=[],acquisition="Share an original failure-case test pack with a specific developer audience.",validation_experiment="Ask three teams to show their current manual checks, then test a paid pilot.",kill_criteria=["No recurring costly pain","Native tooling already solves it economically"],uncertainties=["This example contains no real market evidence."],changes_since_previous="First illustrative assessment.")
    pricing = copy.deepcopy(sources[2])
    pricing.update(id="S4",url="https://example.net/fictional/pricing",kind="pricing",excerpt="Paid analytics plans are available per workspace.",supports="Fictional illustration of a checked pricing model.")
    sources.append(pricing)
    second = copy.deepcopy(pain)
    second.update(id="P2",title="Review history and approvals are scattered",workflow="Collecting approvals and evidence before publishing a recurring metric report",problem="The same analytics team assembles review evidence across spreadsheets and chat.",source_ids=["S1","S2"])
    opportunity["product"] = dict(name="Analytics release assurance",category="Analytics quality and release management",target_customer="Small analytics teams publishing recurring reports",buyer="Analytics engineering lead",job_to_be_done="Publish trustworthy recurring analytics with repeatable checks and review evidence",related_pain_ids=["P1","P2"],workflow_steps=["Replay approved metric checks","Collect exceptions and approvals","Publish a release evidence record"],why_one_product="The same team and release process owns correctness checking and approval evidence.",recurring_value="Each reporting release repeats the workflow, beyond any individual bugfix.",entry_point="One warehouse and one reporting release workflow.",expansion_path="Additional reporting workflows for the same buyer.",scope="standalone_product",incumbent_absorption_risk="Existing analytics platforms may bundle approval and verification features.",source_ids=["S1","S2"],segment_alignment="aligned",segment_alignment_reason="Both fictional accounts represent small analytics teams with the same budget owner and release job.",user_persona="Analytics engineer responsible for recurring customer reports",user_job="Detect metric changes and assemble review evidence before a release",buyer_persona="Analytics engineering lead accountable for report reliability",buyer_goal="Reduce review cost and avoid customer-facing reporting errors",buyer_user_relationship="different_people",purchase_trigger="A recurring release delay or customer-visible metric error makes manual review unacceptable",persona_source_ids=["S1","S2"])
    opportunity["market"] = dict(verdict="supported",category="Analytics quality and release management",target_segment="Small teams accountable for recurring customer reports",buying_signals=[dict(claim="Fictional buyer pays for manual review.",kind="customer_spending",source_ids=["S2"])],reachable_market="Illustrative hypothesis: reach specialist analytics consultancies; actual buyer counts remain unverified.",pricing_logic="Test a workspace subscription against current manual review spending. No validated price.",differentiation="Combine repeatable checks and release approvals in a bounded workflow.",switching_trigger="Manual review becomes a recurring release bottleneck.",competitor_search_notes=["Synthetic comparison of a paid product and manual alternative."],counterevidence=["Existing platforms may cover the entire workflow."],remaining_validation=["All examples are synthetic; interview real buyers."],source_ids=["S2","S3","S4"],acquisition_channels=[dict(name="Specialist analytics consultancies",target_role="Analytics engineering lead",evidence="The fictional accounts represent this buyer role.",source_ids=["S1","S2"])],bottom_up_market_estimate="Illustrative lower bound: 100 reachable consultancies multiplied by one potential workspace; this is test fixture data, not a market claim.",market_size_assumptions=["One workspace per consultancy","The synthetic count exists only to exercise the gate"],product_hunt_checks=[],product_hunt_search_notes=["Synthetic test: Product Hunt category and job searches returned no evidence."])
    opportunity["competitors"][0].update(category="direct",target_customer="Analytics teams",price_evidence="Illustrative paid workspace plan.",pricing_source_ids=["S4"],adoption_evidence="Unknown in this synthetic example.",switching_costs="Migrate existing reports and checks.")
    opportunity["competitors"].append(dict(name="Manual SQL and spreadsheet review",offering="Existing manual release workflow.",price_evidence="Fictional buyer reports paid review time.",gap="Repeated checking and evidence assembly remain manual.",source_ids=["S2"],category="manual",target_customer="The same analytics team",adoption_evidence="Fictional firsthand account.",switching_costs="Document current review practices.",pricing_source_ids=[]))
    return dict(summary="This is a synthetic walkthrough of the workspace. It demonstrates the pain gate, nine-dimensional scorecard, evidence ledger, and feedback controls. Start a scout for real research.",pains=[pain,second],sources=sources,search_notes=["Example data only; no internet search was performed."],limitations=["All people, sources and commercial statements here are fictional."],research_trail=[],opportunities=[opportunity],rejected_directions=["A broad analytics platform is too large a first product for this example."])

def create_demo(store):
    existing = next((r for r in store.all("run") if r.get("demo")),None)
    if existing: return existing
    ctx = store.context()
    run = dict(id="example",keywords="AI data, developer tools",context="Synthetic product walkthrough",days=90,max_opportunities=5,timeout_minutes=20,revision=1,status="completed",stage="complete",message="Synthetic example — no market research performed.",created_at=now(),updated_at=now(),steering=[],profile_snapshot=ctx["profile"],memory_snapshot=ctx["memory"],feedback_snapshot=[],elapsed_seconds=0,checkpoints={},report=evaluate(sample_payload()),usage=[],demo=True,corrections_pending=False)
    for o in run["report"]["opportunities"]:
        o.update(score_changes=[],previous_status=None)
    store.put("run",run["id"],run)
    return run


def synthesis_payload(data):
    return dict(**{k:copy.deepcopy(data[k]) for k in Discovery.model_fields},product_hypotheses=[copy.deepcopy(o["product"]) for o in data["opportunities"] if o.get("product")])
