import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Compass, CircleHelp, Search, Layers3, FileText, Brain, ArrowUpRight, ArrowRight, Plus, X, SlidersHorizontal, Play, Pause, Square, Check, CheckCircle2, Clock3, ExternalLink, ChevronRight, MessageSquare, RotateCcw, Trash2, Bookmark, AlertCircle, Download, Sparkles, BarChart3, Target, Settings2, LoaderCircle, Send, ShieldCheck } from "lucide-react";
import type { Run, RunEvent, Report, Opportunity, Source, Memory, Score, PromptDiscovery, ScoutPrompt } from "./types";
import { dimensions, statusLabel, active } from "./types";
import "./style.css";
import "./steering.css";
import "./research-trail.css";
import "./persona.css";
import "./prompt-discovery.css";
import "./direction-page.css";
import { ProductMarketView } from "./ProductMarket";
import { LiveFindings, ResearchTrail } from "./ResearchTrail";
import { InvestigationForm, InvestigationSummary, FollowupNotice } from "./Investigation";
import type { InvestigationState } from "./Investigation";

async function api<T>(path:string, method="GET", body?:unknown):Promise<T>{
  const response=await fetch("/api"+path,{method,headers:body!==undefined?{"Content-Type":"application/json"}:{},body:body!==undefined?JSON.stringify(body):undefined});
  if(!response.ok){const error=await response.json().catch(()=>({detail:"Request failed"})); throw new Error(typeof error.detail==="string"?error.detail:JSON.stringify(error.detail));}
  return response.json();
}
const date=(s:string)=>new Date(s).toLocaleDateString(undefined,{month:"short",day:"numeric"});
const safeUrl=(s:string)=>/^https?:\/\//i.test(s)?s:undefined;
type View="scout"|"directions"|"opportunities"|"reports"|"memory";
type FeedbackState={run:Run;opportunity?:Opportunity;kind:string};
type Learning={feedback_count:number;outcome_count:number;comparisons:{opportunity:string;predicted_status:string;outcome:string;amount:number|null;reason:string;at:string}[];source_feedback:Record<string,{interested:number;rejected:number;outcomes:number}>;caveat:string};
type Route={view:View;runId?:string;opportunityId?:string};
const parseRoute=(path=window.location.pathname):Route=>{const parts=path.split("/").filter(Boolean).map(decodeURIComponent);if(parts[0]==="opportunities")return{view:"opportunities",runId:parts[1],opportunityId:parts[2]};if(parts[0]==="directions")return{view:"directions"};if(parts[0]==="reports")return{view:"reports"};if(parts[0]==="memory")return{view:"memory"};return{view:"scout",runId:parts[0]==="scout"?parts[1]:undefined};};
const routePath=(view:View,runId?:string,opportunityId?:string)=>view==="scout"?`/scout${runId?"/"+encodeURIComponent(runId):""}`:view==="opportunities"?`/opportunities${runId?"/"+encodeURIComponent(runId):""}${opportunityId?"/"+encodeURIComponent(opportunityId):""}`:`/${view}`;

function App(){
 const [view,setView]=useState<View>(()=>parseRoute().view);
 const [runs,setRuns]=useState<Run[]>([]);
 const [run,setRun]=useState<Run|null>(null);
 const [events,setEvents]=useState<RunEvent[]>([]);
 const [memories,setMemories]=useState<Memory[]>([]);
 const [profile,setProfile]=useState<Record<string,string>>({});
 const [learning,setLearning]=useState<Learning|null>(null);
 const [keywords,setKeywords]=useState("");
 const [context,setContext]=useState("");
 const [settings,setSettings]=useState(false);
 const [profileOpen,setProfileOpen]=useState(false);
 const [days,setDays]=useState(90);
 const [limit,setLimit]=useState(20);
 const [count,setCount]=useState(5);
 const [error,setError]=useState("");
 const [notice,setNotice]=useState("");
 const [busy,setBusy]=useState(false);
 const [detail,setDetail]=useState<Opportunity|null>(null);
 const [reframe,setReframe]=useState<{run:Run;opportunity:Opportunity}|null>(null);
 const [investigation,setInvestigation]=useState<InvestigationState|null>(null);
 const [feedback,setFeedback]=useState<FeedbackState|null>(null);
 const [memoryEdit,setMemoryEdit]=useState<Memory|null>(null);
 const [newMemory,setNewMemory]=useState(false);
 const [filter,setFilter]=useState("all");
 const [comparison,setComparison]=useState(false);
 const [health,setHealth]=useState<{codex_available:boolean}|null>(null);
 const [promptDiscoveries,setPromptDiscoveries]=useState<PromptDiscovery[]>([]);
 const [discovering,setDiscovering]=useState(false);
 const [discoveryFocus,setDiscoveryFocus]=useState("");
 const [selectedDiscovery,setSelectedDiscovery]=useState<string>();

 async function refresh(){
   const [r,m,p,l,h,d]=await Promise.all([api<Run[]>("/runs"),api<Memory[]>("/memory"),api<Record<string,string>>("/profile"),api<Learning>("/learning"),api<{codex_available:boolean}>("/health"),api<PromptDiscovery[]>("/prompt-discoveries")]);
   setRuns(r);setMemories(m);setProfile(p);setLearning(l);setHealth(h);setPromptDiscoveries(d);
   return r;
 }
 useEffect(()=>{refresh().then(r=>{const route=parseRoute();if(route.runId)selectRun(route.runId,route.opportunityId);else{const current=r.find(x=>active(x));if(current&&route.view==="scout"){selectRun(current.id);navigate("scout",current.id,undefined,true);}}}).catch(e=>setError(e.message));const back=()=>{const route=parseRoute();setView(route.view);setDetail(null);if(route.runId)selectRun(route.runId,route.opportunityId);};window.addEventListener("popstate",back);return()=>window.removeEventListener("popstate",back);},[]);
 async function selectRun(id:string,opportunityId?:string){try{const r=await api<Run>("/runs/"+id);setRun(r);setDetail(opportunityId?r.report?.opportunities.find(o=>o.id===opportunityId)||null:null);setEvents([]);}catch(e){setError(String(e));}}
 function navigate(next:View,runId?:string,opportunityId?:string,replace=false){const path=routePath(next,runId,opportunityId);if(window.location.pathname!==path)window.history[replace?"replaceState":"pushState"]({},"",path);setView(next);if(!opportunityId)setDetail(null);}
 useEffect(()=>{
   if(!run || !active(run))return;
   const id=run.id;
   const stream=new EventSource("/api/runs/"+id+"/events");
   stream.onmessage=(event)=>{const e=JSON.parse(event.data) as RunEvent;setEvents(old=>old.some(x=>x.id===e.id)?old:[...old,e].slice(-100));};
   const poll=async()=>{try{const next=await api<Run>("/runs/"+id);setRun(current=>current?.id===id?next:current);if(!active(next))refresh().catch(()=>{});}catch(e){setError(String(e));}};
   stream.addEventListener("idle",()=>{stream.close();poll();});
   const timer=setInterval(poll,2500);
   return()=>{stream.close();clearInterval(timer);};
 },[run?.id,run?.revision,run?.status]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(""),6000);return()=>clearTimeout(t);},[notice]);
 async function start(){
   if(!keywords.trim())return;
   setBusy(true);setError("");
   try{const r=await api<Run>("/runs","POST",{keywords,context,days,max_opportunities:count,timeout_minutes:limit});setRun(r);setEvents([]);setDetail(null);navigate("scout",r.id);await refresh();}
   catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 async function control(action:string){
   if(!run)return;
   try{const r=await api<Run>(`/runs/${run.id}/control/${action}`,"POST");setRun(r);await refresh();}catch(e){setError((e as Error).message);}
 }
 async function example(){try{const exampleRun=await api<Run>("/example","POST");setRun(exampleRun);navigate("opportunities",exampleRun.id);await refresh();}catch(e){setError((e as Error).message);}}
 async function discoverDirections(){setDiscovering(true);setError("");try{const result=await api<PromptDiscovery>("/prompt-discoveries","POST",{focus:discoveryFocus,max_prompts:5,timeout_minutes:8});setPromptDiscoveries(old=>[result,...old.filter(x=>x.id!==result.id)]);setSelectedDiscovery(result.id);}catch(e){setError((e as Error).message);}finally{setDiscovering(false);}}
 function usePrompt(item:ScoutPrompt){setKeywords(item.scout_keywords);setContext(item.scout_context);setSettings(true);navigate("scout");window.scrollTo({top:0,behavior:"smooth"});}
 async function done(message:string){setNotice(message);await refresh();if(run)setRun(await api<Run>("/runs/"+run.id));}
 const realRuns=runs.filter(r=>!r.demo);
 const report=run?.report;
 const visible=report?.opportunities.filter(o=>filter==="all"?!["feature","bugfix"].includes(o.product?.scope||""):o.status===filter)||[];
 const enabledMemory=memories.filter(m=>m.active&&!m.forgotten);
 return <div className="app">
   <aside className="sidebar">
     <button className="brand" onClick={()=>navigate("scout",run&&active(run)?run.id:undefined)}><span className="brand-icon"><Compass size={24}/></span><span>scout<span className="brand-dot">.</span></span></button>
     <div className="workspace-label">YOUR RESEARCH WORKSPACE</div>
     <nav aria-label="Main navigation">{([["scout",Search,"Scout"],["directions",Sparkles,"Directions"],["opportunities",Layers3,"Opportunities"],["reports",FileText,"Reports"],["memory",Brain,"Memory"]] as const).map(([key,Icon,label])=><button key={key} aria-label={label} className={"nav-item "+(view===key?"selected":"")} onClick={()=>navigate(key,key==="scout"&&run&&active(run)?run.id:undefined)}><Icon size={18}/><span>{label}</span>{key==="memory"&&enabledMemory.length>0&&<span className="nav-count">{enabledMemory.length}</span>}</button>)}</nav>
     <div className="sidebar-note"><div className="tiny-icon"><Target size={17}/></div><strong>Built for one.</strong><p>Customer pain first.<br/>Evidence over excitement.</p></div>
     <div className="sidebar-bottom"><button className="nav-item" onClick={()=>setProfileOpen(true)}><Settings2 size={18}/><span>Founder context</span></button><div className="local-status"><span className={"dot "+(health?.codex_available?"":"muted")}/>{health?.codex_available?"Codex available locally":"Checking Codex…"}<span className="version">v0.1</span></div></div>
   </aside>
   <main>
     <header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={14}/><span>{view==="scout"?"New discoveries":view[0].toUpperCase()+view.slice(1)}</span></div><span className="pill outline"><span className="dot"/>Personal workspace</span><button className="mobile-context" aria-label="Edit founder context" onClick={()=>setProfileOpen(true)}><Settings2 size={18}/></button></header>
     {error&&<div className="alert error" role="alert"><AlertCircle size={18}/><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError("")}><X size={16}/></button></div>}
     {notice&&<div className="toast" role="status"><CheckCircle2 size={17}/>{notice}</div>}
     <div className="content">
     {view==="scout"&&<>
       <div className="eyebrow"><span className="small-line"/> FOLLOW THE FRICTION</div>
       <h1>Find a problem<br/><span className="serif">worth solving.</span></h1>
       <p className="intro">Start with a few keywords. Scout finds customer pain, challenges the opportunity,<br className="desktop"/> and shows you what it would take to build a business around it.</p>
       <section className="search-box">
         <label className="sr-only" htmlFor="keywords">What do you want to explore?</label>
         <div className="input-row"><Search size={22}/><textarea id="keywords" value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="AI data infrastructure, developer workflows, MCP…" rows={2} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==="Enter")start();}}/></div>
         {settings&&<div className="search-settings"><label>What else should Scout know?<textarea value={context} onChange={e=>setContext(e.target.value)} placeholder="Skills, customer access, things to avoid, a problem you have noticed…" rows={3}/></label><div className="setting-grid"><label>Recent evidence<select value={days} onChange={e=>setDays(+e.target.value)}><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={180}>Last 6 months</option><option value={365}>Last year</option></select></label><label>Research time limit<select value={limit} onChange={e=>setLimit(+e.target.value)}>{[5,10,20,30,60].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label><label>Detailed opportunities<select value={count} onChange={e=>setCount(+e.target.value)}>{[1,2,3,4,5].map(n=><option key={n} value={n}>Up to {n}</option>)}</select></label></div></div>}
         <div className="search-footer"><button className="text-button" onClick={()=>setSettings(!settings)}><SlidersHorizontal size={16}/>{settings?"Less context":"Add context & limits"}</button><button className="primary" disabled={busy||!keywords.trim()||runs.some(r=>active(r))} onClick={start}>{busy?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>}Start scouting<ArrowRight size={16}/></button></div>
       </section>
       <div className="suggestions"><span>A starting point</span>{["AI data tools","Developer experience","Agent workflows"].map(s=><button key={s} onClick={()=>setKeywords(s)}>{s}<Plus size={12}/></button>)}</div>
       <div className="applied-memory"><Brain size={16}/><span>{enabledMemory.length} preferences guide your search.</span><button onClick={()=>navigate("memory")}>Review memory <ArrowUpRight size={13}/></button></div>
       {run&&!run.demo&&<RunPanel run={run} events={events} onControl={control} onView={()=>{const first=run.parent_run_id&&run.report?run.report.opportunities[0]:undefined;if(first)setDetail(first);navigate("opportunities",run.id,first?.id);}} onSteer={async(message,remember,impact)=>{try{setRun(await api<Run>(`/runs/${run.id}/steer`,"POST",{message,remember,impact}));await refresh();setNotice(remember?"Direction applied and saved for future searches.":"Direction applied to this search.");}catch(e){setError((e as Error).message);}}}/>} 
       {run?.status==="completed"&&!run.demo&&<section className="panel learned-panel"><Brain size={18}/><h3>What Scout learned</h3>{enabledMemory.filter(m=>m.created_at>=run.created_at).length?enabledMemory.filter(m=>m.created_at>=run.created_at).map(m=><p key={m.id}>{m.confirmed?"Saved preference: ":"Tentative observation: "}{m.text}</p>):<p>No new preferences yet. Tell Scout what fits, what does not, or what happened with a customer.</p>}<button className="text-button" onClick={()=>setFeedback({run,kind:"direction"})}>Guide the next search<ArrowRight size={14}/></button></section>}
       {!run&&<div className="principles"><div><span className="step-num">01</span><h3>Find the pain</h3><p>Real customers, real workarounds.<br/>Independent accounts, not hype.</p></div><div><span className="step-num">02</span><h3>Challenge the idea</h3><p>Alternatives, buying evidence,<br/>and the work behind the business.</p></div><div><span className="step-num">03</span><h3>See every dimension</h3><p>Nine scores with evidence.<br/>Clear unknowns. No magic number.</p></div></div>}
       <div className="section-heading"><h2>Research notebook</h2><button className="text-button" onClick={()=>navigate("reports")}>All reports<ArrowUpRight size={14}/></button></div>
       {realRuns.length?<div className="notebook">{realRuns.slice(0,4).map(r=><button className="notebook-row" key={r.id} onClick={()=>{selectRun(r.id);navigate(r.status==="completed"?"opportunities":"scout",r.id);}}><span className="notebook-icon"><FileText size={18}/></span><div><strong>{r.keywords}</strong><span>{date(r.created_at)} · Brief v{r.revision}</span></div><Status value={r.status}/><ArrowUpRight size={17}/></button>)}</div>:<div className="empty-notebook"><div><h3>Your next business starts with a question.</h3><p>Your research and decisions will build up here.</p></div><button className="secondary" onClick={example}>Explore an example<ArrowUpRight size={15}/></button></div>}
     </>}
     {view==="directions"&&<>
       <PageTitle eyebrow="EXPLORE BEFORE YOU COMMIT" title="Discover your next search direction." description="Scout scans recent problems and product momentum, then matches promising directions to your founder context."/>
       <section className="direction-search panel"><div className="direction-search-copy"><h2>Find founder-matched problems</h2><p>Your skills, customer access, budget, interests, and saved preferences shape the search.</p><div className="direction-context">{[profile.skills,profile.interests,profile.customer_access].filter(Boolean).map((value,i)=><span className="pill" key={i}>{value}</span>)}</div></div><label>Optional focus<textarea value={discoveryFocus} onChange={e=>setDiscoveryFocus(e.target.value)} rows={3} placeholder="Leave blank to explore broadly, or narrow it to AI data, regulatory workflows, developer tools…"/></label><button className="primary" disabled={discovering||runs.some(r=>active(r))} onClick={discoverDirections}>{discovering?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>} {discovering?"Searching daily, weekly, and monthly signals…":"Discover directions"}</button></section>
       {promptDiscoveries.length>0&&<div className="direction-history"><FileText size={15}/><select aria-label="Direction discovery run" value={selectedDiscovery||promptDiscoveries[0].id} onChange={e=>setSelectedDiscovery(e.target.value)}>{promptDiscoveries.map(item=><option key={item.id} value={item.id}>{date(item.created_at)} · {item.focus||"Broad founder-context scan"} · {item.result?.prompts.length||0} directions</option>)}</select></div>}
       {(()=>{const selected=promptDiscoveries.find(item=>item.id===(selectedDiscovery||promptDiscoveries[0]?.id));return selected?.result?<PromptSuggestions discovery={selected} onUse={usePrompt}/>:<Empty title="Start with your context, not a keyword." text="Discoveries will appear here with evidence, personas, timing, and open questions."/>;})()}
     </>}
     {view==="opportunities"&&<>
       <PageTitle eyebrow="EVIDENCE, SIDE BY SIDE" title="The opportunity landscape." description="Compare customer pain, business potential, and what it takes to operate solo."/>
       <RunSelect runs={runs} selected={run?.id} onSelect={id=>{selectRun(id);navigate("opportunities",id);}}/>
       {run&&<FollowupNotice run={run} onParent={id=>{selectRun(id);navigate("opportunities",id);}}/>} 
       {run?.reframed_from_run_id&&<div className="followup-notice"><span>Product and market reassessment · original report preserved</span><button className="secondary" onClick={()=>{selectRun(run.reframed_from_run_id!);navigate("opportunities",run.reframed_from_run_id!);}}>Original report<ArrowUpRight size={14}/></button></div>}
       {report&&report.rubric_version!=="2.0"&&!run?.demo&&<div className="alert"><CircleHelp size={16}/><span>This historical report predates product synthesis and market validation. Open a result and choose “Reframe as a product” to reassess it.</span></div>}
       {run?.demo&&<div className="alert demo"><Sparkles size={17}/>Synthetic example. All people, sources, and scores are fictional; feedback is disabled.</div>}
       {run&&run.status!=="completed"&&<div className="alert"><Clock3 size={17}/><span>{run.status==="partial"?"Partial assessment — skeptical review is incomplete.":run.message}</span><button onClick={()=>navigate("scout",run.id)}>View research</button></div>}
       {run?.corrections_pending&&<div className="alert"><AlertCircle size={17}/>You flagged an evidence correction. This historical report needs reassessment.</div>}
       {report?<>{detail?<OpportunityDetail opportunity={detail} report={report} demo={!!run?.demo} canInvestigate={run?.status==="completed"&&!run.demo&&!runs.some(r=>active(r))} onReframe={()=>setReframe({run:run!,opportunity:detail})} onInvestigate={score=>setInvestigation({run:run!,opportunity:detail,score})} onBack={()=>navigate("opportunities",run!.id)} onFeedback={kind=>setFeedback({run:run!,opportunity:detail,kind})}/>:<>
         <div className="report-summary"><span className="report-summary-icon"><Compass size={20}/></span><p>{report.summary}</p></div>
         <ResearchTrail report={report} demo={!!run?.demo}/>
         <div className="list-toolbar"><div className="tabs">{[["all","Products"],["worth_validating","Worth validating"],["watch","Watch"],["reject","Rejected"]].map(([k,l])=><button key={k} className={filter===k?"active":""} onClick={()=>setFilter(k)}>{l}<span>{k==="all"?report.opportunities.filter(o=>!["feature","bugfix"].includes(o.product?.scope||"")).length:report.opportunities.filter(o=>o.status===k).length}</span></button>)}</div><button className="text-button" onClick={()=>setComparison(!comparison)}><BarChart3 size={16}/>{comparison?"Cards":"Compare scores"}</button></div>
         {comparison?<Comparison opportunities={visible} onSelect={o=>{setDetail(o);navigate("opportunities",run!.id,o.id);}}/>:<div className="opportunity-grid">{visible.map((o,i)=><OpportunityCard key={o.id} opportunity={o} pain={report.pains.find(p=>p.id===o.pain_id)!} index={i} onSelect={()=>{setDetail(o);navigate("opportunities",run!.id,o.id);}}/>)}</div>}
         {!visible.length&&<Empty title="Nothing passes this filter." text="A search can return no qualifying opportunities. Research leads and rejected directions are still useful."/>}
         {!!report.rejected_directions.length&&<section className="panel rejected"><h3>Directions we ruled out</h3>{report.rejected_directions.map((s,i)=><p key={i}><X size={15}/>{s}</p>)}</section>}
         <p className="footnote">{report.qualification_note}</p>
       </>}</>:<Empty title="A shortlist starts with evidence." text="Start a scout, choose a previous report, or explore the synthetic example." action={<button className="secondary" onClick={example}>Explore an example<ArrowRight size={15}/></button>}/>}
     </>}
     {view==="reports"&&<>
       <PageTitle eyebrow="A RECORD OF YOUR THINKING" title="Your research, over time." description="Revisit evidence, compare score changes, and export the full research trail."/>
       {runs.length?<div className="report-list">{runs.map(r=><div className="report-row panel" key={r.id}><div className="report-row-top"><FileText size={21}/><div><h3>{r.keywords}</h3>{r.reframed_from_run_id&&<p className="followup-label">Product & market reassessment</p>}{r.parent_run_id&&<p className="followup-label">Follow-up · {dimensions[r.focus_dimension!]}</p>}<p>{date(r.created_at)} · Brief v{r.revision} · {r.demo?"Synthetic example":Math.round(r.elapsed_seconds/60)+" minutes of research"}</p></div><Status value={r.status}/></div><div className="report-actions"><button className="secondary" onClick={()=>{selectRun(r.id);navigate("opportunities",r.id);}}>Open report<ArrowUpRight size={15}/></button><div className="export-links"><Download size={14}/>{["md","html","json","csv"].map(f=><a key={f} href={`/api/runs/${r.id}/export/${f}`}>{f.toUpperCase()}</a>)}</div>{!r.demo&&<button className="text-button" onClick={()=>{setKeywords(r.keywords);setContext(r.context);navigate("scout");}}>Scout this again<RotateCcw size={14}/></button>}{!r.demo&&<button className="text-button" onClick={()=>setFeedback({run:r,kind:"direction"})}><MessageSquare size={14}/>Give feedback</button>}</div></div>)}</div>:<Empty title="The notebook is open." text="Complete your first scout to save a research report here."/>}
       {learning&&<section className="panel outcomes"><div className="section-heading"><h2>Reality checks</h2><span className="pill">{learning.outcome_count} outcomes recorded</span></div><p className="muted-text">Customer interviews and paid pilots help calibrate earlier assessments.</p>{learning.comparisons.length?learning.comparisons.map((c,i)=><div className="outcome-row" key={i}><strong>{c.opportunity}</strong><p>{statusLabel(c.predicted_status)} → {c.outcome}{c.amount!==null?" · Amount reported: "+c.amount:""}</p><p>{c.reason}</p></div>):<p className="footnote">Record an outcome from an opportunity card after testing it with real customers.</p>}</section>}
     </>}
     {view==="memory"&&<>
       <PageTitle eyebrow="ADAPTIVE, NEVER INVISIBLE" title="What Scout is learning." description="Your preferences guide the search. They never rewrite the market evidence." action={<button className="primary" onClick={()=>setNewMemory(true)}><Plus size={16}/>Add preference</button>}/>
       <div className="memory-stats"><div><strong>{enabledMemory.length}</strong><span>Active preferences</span></div><div><strong>{memories.filter(m=>m.active&&m.kind==="inferred").length}</strong><span>Tentative observations</span></div><div><strong>{learning?.feedback_count||0}</strong><span>Feedback interactions</span></div></div>
       <div className="memory-list">{memories.map(m=><div className={"memory-card panel "+(!m.active?"disabled-memory":"")} key={m.id}><div className="memory-card-icon"><Brain size={19}/></div><div className="memory-card-content"><div className="memory-labels"><span className={"pill "+(m.kind==="inferred"&&!m.confirmed?"amber":"")}>{m.forgotten?"Forgotten":m.confirmed?"Explicit / confirmed":"Tentative observation"}</span>{!m.active&&!m.forgotten&&<span className="pill">Disabled</span>}<span className="micro">v{m.history.length+1}</span></div><p>{m.forgotten?"Removed from future research context. Historical reports keep their original context.":m.text}</p><details><summary>Why Scout remembers this</summary><p className="footnote">{m.origins.join(" · ")}</p><p className="footnote">Updated {date(m.updated_at)} · {m.history.length} earlier versions</p></details></div><div className="memory-actions">{!m.forgotten&&<><button title="Edit preference" onClick={()=>setMemoryEdit(m)}><SlidersHorizontal size={16}/></button><button title={m.active?"Disable preference":"Enable preference"} onClick={async()=>{try{await api("/memory/"+m.id,"PUT",{text:m.text,active:!m.active,confirmed:m.confirmed});await done(m.active?"Preference disabled.":"Preference enabled.");}catch(e){setError(String(e));}}}>{m.active?<Pause size={16}/>:<Play size={16}/>}</button><button title="Forget preference" onClick={async()=>{try{await api("/memory/"+m.id,"DELETE");await done("Preference forgotten. You can undo this.");}catch(e){setError(String(e));}}}><Trash2 size={16}/></button></>}{m.history.length>0&&<button title="Undo last memory change" onClick={async()=>{try{await api("/memory/"+m.id+"/undo","POST");await done("Earlier memory version restored.");}catch(e){setError(String(e));}}}><RotateCcw size={16}/></button>}</div></div>)}</div>
       <section className="panel"><h3>Learning without an echo chamber</h3><p className="muted-text">Explicit directions apply immediately. Similar feedback on two different opportunities can become a tentative preference. About one fifth of discovery explores adjacent ideas within your constraints.</p><p className="footnote">Bookmarks show interest. Customer outcomes inform calibration. Neither changes the original evidence. No underlying model is retrained.</p></section>
       {learning&&Object.keys(learning.source_feedback).length>0&&<section className="panel"><h3>Source usefulness</h3>{Object.entries(learning.source_feedback).map(([domain,s])=><div className="source-stat" key={domain}><strong>{domain}</strong><span>{s.interested} interested · {s.rejected} rejected · {s.outcomes} outcomes</span></div>)}<p className="footnote">{learning.caveat}</p></section>}
     </>}
     </div>
     <footer>Built around customer pain.<span>Local storage · Public web research · Your judgment</span></footer>
   </main>
   {reframe&&<ReframeModal title={reframe.opportunity.title} onClose={()=>setReframe(null)} onSubmit={async body=>{const child=await api<Run>(`/runs/${reframe.run.id}/reframe`,"POST",{...body,opportunity_id:reframe.opportunity.id});setRun(child);setDetail(null);setEvents([]);setFilter("all");setReframe(null);navigate("scout",child.id);await refresh();setNotice("Researching the broader product and market. Original report preserved.");}}/>}
   {investigation&&<Modal title={"Investigate "+dimensions[investigation.score.dimension]} onClose={()=>setInvestigation(null)}><InvestigationForm value={investigation} onSubmit={async body=>{const child=await api<Run>(`/runs/${investigation.run.id}/investigate`,"POST",body);setRun(child);setDetail(null);setEvents([]);setFilter("all");setInvestigation(null);navigate("scout",child.id);await refresh();setNotice("Focused research started. The original report is preserved.");}}/></Modal>}
   {feedback&&<FeedbackModal value={feedback} onClose={()=>setFeedback(null)} onSave={async body=>{await api("/feedback","POST",body);setFeedback(null);await done("Feedback saved. Scout will use it in future research.");}}/>}
   {(memoryEdit||newMemory)&&<MemoryModal memory={memoryEdit} onClose={()=>{setMemoryEdit(null);setNewMemory(false);}} onSave={async text=>{if(memoryEdit)await api("/memory/"+memoryEdit.id,"PUT",{text,active:true,confirmed:true});else await api("/memory","POST",{text,active:true,confirmed:true});setMemoryEdit(null);setNewMemory(false);await done("Preference saved and visible in future research.");}}/>}
   {profileOpen&&<ProfileModal profile={profile} onClose={()=>setProfileOpen(false)} onSave={async p=>{await api("/profile","PUT",p);setProfile(p);setProfileOpen(false);setNotice("Founder context saved for future searches.");}}/>}
 </div>
}

function Status({value}:{value:string}){return <span className={"pill status "+value}>{["queued","running"].includes(value)&&<LoaderCircle size={12} className="spin"/>}{statusLabel(value)}</span>}
function PromptSuggestions({discovery,onUse}:{discovery:PromptDiscovery;onUse:(item:ScoutPrompt)=>void}){
 const result=discovery.result!;
 return <section className="prompt-results"><div className="prompt-results-head"><div><span className="eyebrow">FOUNDER-MATCHED SHORTLIST</span><h2>Directions worth investigating</h2><p>{result.summary}</p></div><div className="prompt-result-stats"><span><strong>{result.prompts.length}</strong> directions</span><span><strong>{result.sources.length}</strong> sources</span><span><strong>{result.searches.length}</strong> searches</span></div></div><div className="prompt-list">{result.prompts.map((item,index)=>{const sources=result.sources.filter(source=>item.source_ids.includes(source.id));return <article className="prompt-card" key={item.id}><div className="prompt-rank">{String(index+1).padStart(2,"0")}</div><div className="prompt-main"><span className="eyebrow">PROBLEM TO SCOUT</span><h3>{item.title}</h3><p className="prompt-problem">{item.problem_signal}</p><div className="prompt-persona-flow"><div><small>DAILY USER</small><strong>{item.user_persona}</strong></div><ArrowRight size={15}/><div><small>ECONOMIC BUYER</small><strong>{item.buyer_persona}</strong></div></div><div className="prompt-reasons"><div><small>WHY IT FITS YOU</small><p>{item.why_founder_fit}</p></div><div><small>WHY NOW</small><p>{item.why_now}</p></div></div><div className="prompt-card-footer">{item.uncertainties.length>0&&<details><summary>{item.uncertainties.length} open question{item.uncertainties.length===1?"":"s"}</summary><ul>{item.uncertainties.map((u,i)=><li key={i}>{u}</li>)}</ul></details>}<button className="primary" onClick={()=>onUse(item)}>Use as scout brief<ArrowRight size={14}/></button></div></div><aside className="prompt-evidence"><div className="prompt-evidence-title"><strong>Evidence preview</strong><span>{sources.length}</span></div>{sources.slice(0,3).map(source=><a key={source.id} href={safeUrl(source.url)} target="_blank" rel="noreferrer"><span className="pill">{source.signal_type.replaceAll("_"," ")}</span><strong>{source.title}</strong><p>{source.excerpt}</p><small>{source.published_at||"Date unknown"}<ArrowUpRight size={10}/></small></a>)}{!sources.length&&<p className="muted-text">No source preview was returned. Treat this direction as weak.</p>}</aside></article>;})}</div>{result.limitations.length>0&&<details className="prompt-limitations"><summary>Discovery limitations</summary><ul>{result.limitations.map((item,i)=><li key={i}>{item}</li>)}</ul></details>}</section>;
}
function PageTitle({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <div className="page-title"><div><div className="eyebrow"><span className="small-line"/>{eyebrow}</div><h1 className="smaller">{title}</h1><p className="intro">{description}</p></div>{action}</div>}
function Empty({title,text,action}:{title:string;text:string;action?:React.ReactNode}){return <div className="empty"><span className="empty-icon"><Compass size={30}/></span><h2>{title}</h2><p>{text}</p>{action}</div>}
function RunSelect({runs,selected,onSelect}:{runs:Run[];selected?:string;onSelect:(id:string)=>void}){return runs.length?<div className="run-select"><FileText size={16}/><select aria-label="Select research run" value={selected||""} onChange={e=>onSelect(e.target.value)}><option value="" disabled>Select a research run</option>{runs.map(r=><option key={r.id} value={r.id}>{r.keywords}{r.reframed_from_run_id?" · Product & market reassessment":""}{r.parent_run_id?" · "+dimensions[r.focus_dimension!]+" follow-up":""}{r.demo?" · Example":" · "+date(r.created_at)} · {statusLabel(r.status)}</option>)}</select></div>:null}
function RunPanel({run,events,onControl,onView,onSteer}:{run:Run;events:RunEvent[];onControl:(s:string)=>void;onView:()=>void;onSteer:(m:string,r:boolean,i:string)=>Promise<void>}){
 const [message,setMessage]=useState("");const [remember,setRemember]=useState(false);const [impact,setImpact]=useState("auto");const [sending,setSending]=useState(false);
 const stages=run.parent_run_id?["investigate","verify_investigation","complete"]:["discover","pain","synthesis","market_scan","assessment","challenge","complete"];const stageIndex=stages.indexOf(run.stage);
 return <section className="run-panel panel"><div className="run-panel-head"><div><span className="eyebrow">CURRENT SCOUT · BRIEF V{run.revision}</span><h2>{run.keywords}</h2></div><Status value={run.status}/></div>
 <div className="steps">{(run.parent_run_id?["Focused evidence","Verification","Updated score"]:["Signals","Customer pain","Product thesis","Market evidence","Scoring","Challenge","Report"]).map((s,i)=><div key={s} className={(i===stageIndex?"current ":"")+(i<stageIndex?"done":"")}><span>{i<stageIndex?<Check size={12}/>:i+1}</span>{s}</div>)}</div>
 <p className="run-message">{run.message}</p>{run.parent_run_id&&<p className="footnote">Focus: {dimensions[run.focus_dimension!]} · {run.parent_opportunity_title}. The parent report remains unchanged.</p>}
 <LiveFindings run={run}/>
 {!!run.steering.length&&<div className="steering-history">{run.steering.map(s=><p key={s.revision}><MessageSquare size={14}/>{s.message}<span>{steeringLabel(s.resolved_impact)} · resumes at {stageLabel(s.restart_from)}{s.remember?" · remembered":""}</span></p>)}</div>}
 {events.length>0&&<details className="research-log"><summary>{events.filter(e=>e.type!=="heartbeat").length} research events · see the trail</summary><div>{events.slice(-30).map(e=><p key={e.id}><time>{new Date(e.at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time>{e.message}</p>)}</div></details>}
 <div className="run-controls">{active(run)&&<><button className="secondary" onClick={()=>onControl("pause")}><Pause size={14}/>Pause</button><button className="text-button" onClick={()=>onControl("cancel")}><Square size={13}/>Stop</button></>}{["paused","partial","failed"].includes(run.status)&&<button className="secondary" onClick={()=>onControl("resume")}><Play size={14}/>Resume research</button>}{run.report&&<button className="primary" onClick={onView}>View scorecards<ArrowRight size={15}/></button>}</div>
 {["running","queued","paused","partial","failed"].includes(run.status)&&<form className="steer-form" onSubmit={async e=>{e.preventDefault();if(!message.trim())return;setSending(true);try{await onSteer(message,remember,impact);setMessage("");}finally{setSending(false);}}}><label htmlFor="steer">Steer the search</label><div><input id="steer" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Focus on tools developers can adopt themselves…"/><button className="icon-primary" aria-label="Apply direction" disabled={sending||!message.trim()}><Send size={16}/></button></div><div className="steer-options"><label>What changes?<select aria-label="Steering impact" value={impact} onChange={e=>setImpact(e.target.value)}><option value="auto">Auto-detect impact</option><option value="source_refinement">Sources and evidence only</option><option value="market_refinement">Market, competitors, pricing</option><option value="product_reframing">Product and solution</option><option value="full_restart">Customer or problem — restart</option></select></label><label className="checkbox"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Remember for future searches</label></div></form>}
 </section>
}
const steeringLabel=(s?:string)=>({source_refinement:"Source refinement",market_refinement:"Market refinement",product_reframing:"Product reframing",full_restart:"Full restart"}[s||""]||"Auto-classified");
const stageLabel=(s?:string)=>({signals:"signals",pain:"customer pain",synthesis:"product synthesis",market_scan:"market evidence",assessment:"scoring",challenge:"skeptical review",investigate:"focused evidence",verify_investigation:"verification"}[s||""]||s||"research");
function ScoreBars({value}:{value:number|null}){return <div className="score-bars">{[1,2,3,4,5].map(n=><i key={n} className={value!==null&&n<=value?"filled":""}/>)}<span>{value===null?"?":value}</span></div>}
function OpportunityCard({opportunity:o,pain,index,onSelect}:{opportunity:Opportunity;pain:Report["pains"][number];index:number;onSelect:()=>void}){
 return <button className="opportunity-card" onClick={onSelect}><div className="card-top"><span className="card-index">{String(index+1).padStart(2,"0")}</span><Status value={o.status}/><ArrowUpRight size={18}/></div><h2>{o.title}</h2><p>{o.product?.job_to_be_done||pain.problem}</p>{o.product&&<span className="pill product-card-tag">{o.product.related_pain_ids.length} connected pains · {o.product.category}</span>}<div className="buyer"><Target size={14}/>{o.buyer}</div><div className="card-score-preview">{["pain_severity","willingness_to_pay","solo_feasibility"].map(k=>{const s=o.scores.find(x=>x.dimension===k)!;return <div key={k}><span>{dimensions[k]}</span><ScoreBars value={s.value}/></div>})}</div><div className="card-bottom"><span><MessageSquare size={14}/>{pain.independent_accounts} independent accounts</span><span>Full scorecard<ChevronRight size={14}/></span></div></button>
}
function Comparison({opportunities,onSelect}:{opportunities:Opportunity[];onSelect:(o:Opportunity)=>void}){return <div className="comparison"><table><thead><tr><th>Opportunity</th>{Object.values(dimensions).map(d=><th key={d}>{d}</th>)}</tr></thead><tbody>{opportunities.map(o=><tr key={o.id}><td><button onClick={()=>onSelect(o)}>{o.title}</button><Status value={o.status}/></td>{Object.keys(dimensions).map(d=>{const s=o.scores.find(s=>s.dimension===d)!;return <td key={d} title={s.rationale}><strong>{s.value===null?"?":s.value+"/5"}</strong><small>{s.confidence}</small></td>})}</tr>)}</tbody></table><p className="footnote">Higher is more favorable in every dimension. Unknown is not zero. Confidence is separate from attractiveness.</p></div>}
function Citation({id,sources,demo}:{id:string;sources:Source[];demo:boolean}){const s=sources.find(s=>s.id===id);return s?<a className="citation" href={demo?undefined:safeUrl(s.url)} target="_blank" rel="noreferrer" title={s.title}>{id}<ArrowUpRight size={10}/></a>:<span className="citation">{id}</span>}
function OpportunityDetail({opportunity:o,report,demo,canInvestigate,onInvestigate,onReframe,onBack,onFeedback}:{opportunity:Opportunity;report:Report;demo:boolean;canInvestigate:boolean;onInvestigate:(score:Score)=>void;onReframe:()=>void;onBack:()=>void;onFeedback:(k:string)=>void}){
 const pain=report.pains.find(p=>p.id===o.pain_id)!;const [tab,setTab]=useState(report.investigation?"scorecard":"product");
 return <div className="opportunity-detail"><button className="text-button back" onClick={onBack}>← All opportunities</button><div className="detail-title"><Status value={o.status}/><h1 className="smaller">{o.title}</h1><p className="intro">{o.thesis}</p><div className="detail-actions"><button disabled={demo||!canInvestigate} className="secondary" onClick={onReframe}><Layers3 size={15}/>Reframe as a product</button><button disabled={demo} className="secondary" onClick={()=>onFeedback("interested")}><Bookmark size={15}/>Interested</button><button disabled={demo} className="secondary" onClick={()=>onFeedback("reject")}><X size={15}/>Not for me</button><button disabled={demo} className="secondary" onClick={()=>onFeedback("correction")}><MessageSquare size={15}/>Correct evidence</button><button disabled={demo} className="primary" onClick={()=>onFeedback("outcome")}><CheckCircle2 size={15}/>Record outcome</button></div></div>
 <InvestigationSummary report={report}/>
 <div className="pain-callout"><Target size={21}/><div><span className="eyebrow">THE CUSTOMER PAIN</span><p>{pain.problem}</p><div className="evidence-line"><span className={"pill "+(pain.qualified?"green":"amber")}>{pain.independent_accounts} independent firsthand accounts</span>{pain.source_ids.map(id=><Citation key={id} id={id} sources={report.sources} demo={demo}/>)}</div><small>{pain.gate_reason}</small></div></div>
 <div className="tabs detail-tabs">{[["product","Product & market"],["scorecard","Scorecard"],["pain","Pain & evidence"],["execution","Building it solo"],["validation","Challenge & validate"]].map(([k,l])=><button className={tab===k?"active":""} key={k} onClick={()=>setTab(k)}>{l}</button>)}</div>
 {tab==="product"&&<ProductMarketView opportunity={o} report={report} demo={demo}/>}
 {tab==="scorecard"&&<><div className="score-grid">{o.scores.map(s=><div className="score-card panel" key={s.dimension}><div className="score-title"><h3>{dimensions[s.dimension]}</h3><span className={"confidence "+s.confidence}>{s.confidence} confidence</span></div><div className="score-value"><strong>{s.value===null?"Unknown":s.value}<span>{s.value!==null?"/ 5":""}</span></strong><ScoreBars value={s.value}/></div><p>{s.rationale}</p><div>{s.source_ids.map(id=><Citation key={id} id={id} sources={report.sources} demo={demo}/>)}</div><details><summary>What could change this score?</summary><p>{s.next_evidence}</p><p><strong>Assumptions:</strong> {s.assumptions.join(" ")||"None recorded."}</p><p><strong>Counterevidence:</strong> {s.counterevidence}</p></details><button className="text-button investigate-button" aria-label={"Investigate "+dimensions[s.dimension]} disabled={demo||!canInvestigate} onClick={()=>onInvestigate(s)}><Search size={13}/>{s.value===null?"Investigate this unknown":"Investigate further"}</button></div>)}</div><section className="panel"><h3>Why this ranks here</h3><p>{o.ranking_reason}</p><h3>Founder fit · assessed separately</h3><p>{o.founder_fit}</p>{!!o.score_changes?.length&&<><h3>Changes since the previous report</h3>{o.score_changes.map(c=><p key={c.dimension}>{dimensions[c.dimension]}: {c.before??"Unknown"} → {c.after??"Unknown"}</p>)}</>}<p className="footnote">{o.changes_since_previous}</p></section></>}
 {tab==="pain"&&<><div className="facts-grid">{[["Customer",pain.customer],["Buyer",pain.buyer],["Workflow",pain.workflow],["Frequency",pain.frequency],["Consequence",pain.consequence],["Current workaround",pain.workaround],["Spending evidence",pain.spending_evidence],["Why now",o.why_now]].map(([k,v])=><div className="panel" key={k}><span className="eyebrow">{k}</span><p>{v}</p></div>)}</div><h2 className="section-title">Evidence ledger</h2>{report.sources.map(s=><article className="source-card panel" key={s.id}><div className="source-header"><span className="citation">{s.id}</span><span className="pill">{s.kind}</span>{s.stale&&<span className="pill amber">Older evidence</span>}{s.duplicate&&<span className="pill amber">Duplicate origin</span>}{!s.usable&&<span className="pill amber">Unusable</span>}</div><h3>{demo?s.title:<a href={safeUrl(s.url)} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={14}/></a>}</h3><p className="micro">{s.speaker||"Author unknown"} · Published {s.published_at||"date unknown"} · Retrieved {s.retrieved_at}</p><blockquote>{s.excerpt}</blockquote><p>{s.supports}</p></article>)}</>}
 {tab==="execution"&&<><section className="panel"><span className="eyebrow">THE NARROW PRODUCT</span><h2>{o.solution}</h2><p>{o.mvp}</p></section><div className="facts-grid">{[["Build effort",o.build_effort],["Upfront costs",o.upfront_cost],["Monthly costs",o.monthly_cost],["Support burden",o.support_burden],["Sales effort",o.sales_effort],["Time to a pilot",o.time_to_pilot]].map(([k,v])=><div className="panel" key={k}><span className="eyebrow">{k}</span><p>{v}</p></div>)}</div><ListPanel title="Dependencies" items={o.dependencies}/><ListPanel title="Unresolved solo blockers" items={o.solo_blockers}/><ListPanel title="Conflicts with your constraints" items={o.constraint_conflicts}/><section className="panel"><h3>Reaching customers</h3><p>{o.acquisition}</p></section></>}
 {tab==="validation"&&<><section className="panel validation-panel"><ShieldCheck size={24}/><h2>Test the business before building it.</h2><p>{o.validation_experiment}</p></section><ListPanel title="Kill criteria" items={o.kill_criteria}/><h2 className="section-title">Alternatives checked</h2>{o.competitors.map((c,i)=><section className="panel" key={i}><h3>{c.name}</h3><p>{c.offering}</p><p><strong>Price evidence:</strong> {c.price_evidence}</p><p><strong>Proposed gap:</strong> {c.gap}</p>{c.source_ids.map(id=><Citation key={id} id={id} sources={report.sources} demo={demo}/>)}</section>)}<ListPanel title="Unknowns" items={o.uncertainties}/><ListPanel title="Evidence checks" items={o.warnings}/><ListPanel title="Research limitations" items={report.limitations.concat(report.validation_issues)}/></>}
 </div>
}
function ListPanel({title,items}:{title:string;items:string[]}){return items.length?<section className="panel"><h3>{title}</h3><ul>{items.map((s,i)=><li key={i}>{s}</li>)}</ul></section>:null}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();};document.addEventListener("keydown",listener);const old=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",listener);document.body.style.overflow=old;};},[onClose]);
 return <div className="modal-backdrop" onClick={onClose}><div className="modal" role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</div></div>
}
function FeedbackModal({value,onClose,onSave}:{value:FeedbackState;onClose:()=>void;onSave:(v:unknown)=>Promise<void>}){
 const [reason,setReason]=useState("");const [remember,setRemember]=useState(false);const [tag,setTag]=useState("");const [outcome,setOutcome]=useState("interview");const [amount,setAmount]=useState("");const [err,setErr]=useState("");const [saving,setSaving]=useState(false);
 const title=({interested:"What makes this interesting?",reject:"What doesn't fit?",correction:"Correct the evidence",outcome:"Record a real-world outcome",direction:"Guide future scouting"} as Record<string,string>)[value.kind]||"Give Scout feedback";
 return <Modal title={title} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setSaving(true);try{await onSave({run_id:value.run.id,opportunity_id:value.opportunity?.id||null,kind:value.kind,reason,remember,preference_tag:tag||null,outcome:value.kind==="outcome"?outcome:null,amount:amount?+amount:null});}catch(e){setErr((e as Error).message);setSaving(false);}}}><p className="muted-text">{value.opportunity?.title}</p><label>{value.kind==="outcome"?"What happened?":"Tell Scout why"}<textarea autoFocus required rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder={value.kind==="correction"?"Which claim or source is wrong? What should be checked?":"A specific reason helps Scout improve its next search."}/></label>{["reject","direction"].includes(value.kind)&&<><label>Optional preference signal<select value={tag} onChange={e=>setTag(e.target.value)}><option value="">Let Scout interpret the feedback cautiously</option><option value="self_serve">Prefer self-serve adoption</option><option value="low_operations">Less support and operating work</option><option value="emerging_markets">Stronger emerging demand</option><option value="solo_buildable">More feasible for one founder</option><option value="accessible_data">More accessible data</option></select></label><label className="checkbox"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Save my reason as a lasting personal preference</label></>}{value.kind==="outcome"&&<div className="setting-grid"><label>Outcome<select aria-label="Outcome" value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="interview">Customer interview</option><option value="pilot">Pilot agreed</option><option value="paid">Customer paid</option><option value="no_demand">No demand found</option><option value="other">Other</option></select></label><label>Amount, if applicable<input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Include currency in your note"/></label></div>}{err&&<p className="error-text">{err}</p>}<p className="footnote">{value.kind==="correction"?"Source corrections trigger reassessment; they are not saved as personal preferences.":"Feedback affects future prioritization. It does not rewrite the original market evidence."}</p><button className="primary" disabled={saving||!reason.trim()}>{saving?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>}Save feedback</button></form></Modal>
}
function MemoryModal({memory,onClose,onSave}:{memory:Memory|null;onClose:()=>void;onSave:(s:string)=>Promise<void>}){
 const [text,setText]=useState(memory?.text||"");const [err,setErr]=useState("");const [saving,setSaving]=useState(false);
 return <Modal title={memory?"Edit preference":"Add a lasting preference"} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setSaving(true);try{await onSave(text);}catch(e){setErr((e as Error).message);setSaving(false);}}}><label>What should Scout remember?<textarea autoFocus value={text} onChange={e=>setText(e.target.value)} rows={5} placeholder="I prefer developer tools that customers can adopt without a sales call."/></label><p className="footnote">Saved as your explicit preference. You can disable it or undo changes at any time.</p>{err&&<p className="error-text">{err}</p>}<button className="primary" disabled={saving||!text.trim()}><Check size={16}/>Save preference</button></form></Modal>
}
function ProfileModal({profile,onClose,onSave}:{profile:Record<string,string>;onClose:()=>void;onSave:(p:Record<string,string>)=>Promise<void>}){
 const [p,setP]=useState(profile);const [err,setErr]=useState("");const [saving,setSaving]=useState(false);
 return <Modal title="Your founder context" onClose={onClose}><p className="muted-text">Optional context makes feasibility personal. Leave a field blank and Scout will treat it as unknown.</p><form onSubmit={async e=>{e.preventDefault();setSaving(true);try{await onSave(p);}catch(e){setErr((e as Error).message);setSaving(false);}}}>{[["skills","Skills & experience"],["interests","Interests"],["customer_access","Customers or communities you can reach"],["geography","Markets & geography"],["time_available","Time available"],["budget","Budget or financial limits"],["assets","Existing assets, code, or data"],["exclusions","Hard exclusions"]].map(([k,l],i)=><label key={k}>{l}<textarea autoFocus={i===0} rows={2} value={p[k]||""} onChange={e=>setP({...p,[k]:e.target.value})}/></label>)}{err&&<p className="error-text">{err}</p>}<button className="primary" disabled={saving}><Check size={16}/>Save context</button></form></Modal>
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);

function ReframeModal({title,onClose,onSubmit}:{title:string;onClose:()=>void;onSubmit:(body:{guidance:string;timeout_minutes:number})=>Promise<void>}){
 const [guidance,setGuidance]=useState("Find the broader recurring customer job behind these issues. Group related pains into a coherent standalone product, compare competitors and substitutes, and establish buying evidence and a reachable market. Do not simply rename a tiny feature or propose an all-in-one platform.");
 const [minutes,setMinutes]=useState(20);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 return <Modal title="Research the product and market" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setSaving(true);try{await onSubmit({guidance,timeout_minutes:minutes});}catch(e){setError((e as Error).message);setSaving(false);}}}><p className="muted-text">Starting evidence: {title}</p><label>What should the product research focus on?<textarea autoFocus value={guidance} onChange={e=>setGuidance(e.target.value)} maxLength={5000} rows={5}/></label><label>Research time limit<select aria-label="Product research time limit" value={minutes} onChange={e=>setMinutes(+e.target.value)}>{[10,20,30,60].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label><p className="footnote">Creates a fresh research run with product synthesis and market validation. The old solution can change or be rejected. Uses your Codex allowance.</p>{error&&<p className="error-text" role="alert">{error}</p>}<button className="primary" disabled={saving}><Search size={15}/>Research product & market</button></form></Modal>
}
