import { CheckCircle2, CircleHelp, ArrowUpRight, Layers3 } from "lucide-react";
import type { Opportunity, Report } from "./types";

function Refs({ids,report,demo}:{ids:string[];report:Report;demo:boolean}){
 return <>{ids.map(id=>{const s=report.sources.find(s=>s.id===id);return s?<a className="citation" key={id} href={!demo&&/^https?:\/\//.test(s.url)?s.url:undefined} target="_blank" rel="noreferrer" title={s.title}>{id}<ArrowUpRight size={10}/></a>:null;})}</>;
}
export function ProductMarketView({opportunity:o,report,demo}:{opportunity:Opportunity;report:Report;demo:boolean}){
 const product=o.product,market=o.market;
 return <>
  {market&&<section className="panel"><h3>Product Hunt landscape</h3>{(market.product_hunt_checks||[]).length?(market.product_hunt_checks||[]).map((p,i)=><div className="investigation-finding" key={i}><strong><a href={p.url} target="_blank" rel="noreferrer">{p.product_name}<ArrowUpRight size={11}/></a></strong><p>{p.positioning}</p><p>{p.relevance}</p><Refs ids={p.source_ids} report={report} demo={demo}/></div>):<p>No relevant Product Hunt products were recorded.</p>}<ul>{(market.product_hunt_search_notes||[]).map((n,i)=><li key={i}>{n}</li>)}</ul><p className="footnote">Launches and votes show attention and positioning, not revenue or willingness to pay.</p></section>}
  {!product&&<div className="alert"><CircleHelp size={18}/><span>This report has no product-level assessment. Use “Reframe as a product” to connect related pains and research the market.</span></div>}
  {o.market_checks&&<section className="panel market-gates"><h3>Product and market qualification</h3><div className="gate-row">{([["product_supported","Coherent product"],["competition_checked","Alternatives checked"],["market_supported","Supported market case"]] as const).map(([key,label])=><span className={"pill "+(o.market_checks![key]?"green":"amber")} key={key}>{o.market_checks![key]?<CheckCircle2 size={13}/>:<CircleHelp size={13}/>} {label}</span>)}{product?.user_persona&&<span className={"pill "+((o.market_checks as any).persona_supported?"green":"amber")}>{(o.market_checks as any).persona_supported?<CheckCircle2 size={13}/>:<CircleHelp size={13}/>} Personas supported</span>}</div>{o.market_checks.reasons.map((r,i)=><p key={i}>{r}</p>)}<p className="footnote">Desk research supports a hypothesis. Customer interviews and paid pilots still need to validate the product.</p></section>}
  {product&&<>
   <section className="panel product-thesis"><span className="eyebrow"><Layers3 size={14}/>{product.category}</span><h2>{product.name}</h2><p className="product-job">{product.job_to_be_done}</p><div className="gate-row"><span className="pill">{product.scope.replaceAll("_"," ")}</span><span className="pill">{product.related_pain_ids.length} related pains</span></div><Refs ids={product.source_ids} report={report} demo={demo}/></section>
   <section className="panel persona-map"><div className="gate-row"><h3>User and buyer</h3><span className={"pill "+(product.buyer_user_relationship&&product.buyer_user_relationship!=="unknown"?"green":"amber")}>{product.buyer_user_relationship==="same_person"?"Same person":product.buyer_user_relationship==="different_people"?"Different people":"Relationship unverified"}</span></div><div className="persona-columns"><div><span className="eyebrow">DAILY USER</span><h3>{product.user_persona||"User persona not established"}</h3><p>{product.user_job||"The daily workflow and desired outcome still need evidence."}</p></div><ArrowUpRight className="persona-arrow" size={18}/><div><span className="eyebrow">ECONOMIC BUYER</span><h3>{product.buyer_persona||product.buyer||"Buyer persona not established"}</h3><p>{product.buyer_goal||"The budget owner's goal still needs evidence."}</p></div></div><p><strong>Purchase trigger:</strong> {product.purchase_trigger||"Not established."}</p><Refs ids={product.persona_source_ids||[]} report={report} demo={demo}/></section>
   <section className="panel"><h3>Customer-segment alignment</h3><div className="gate-row"><span className={"pill "+(product.segment_alignment==="aligned"?"green":"amber")}>{product.segment_alignment||"Not assessed"}</span></div><p>{product.segment_alignment_reason||"This report predates explicit segment-alignment checks."}</p></section>
   <div className="facts-grid">{[["Target customer",product.target_customer],["Budget owner",product.buyer],["Why one product",product.why_one_product],["Recurring value",product.recurring_value],["Initial product",product.entry_point],["Expansion for the same buyer",product.expansion_path]].map(([k,v])=><section className="panel" key={k}><span className="eyebrow">{k}</span><p>{v}</p></section>)}</div>
   <section className="panel product-workflow"><h3>The complete workflow</h3><ol>{product.workflow_steps.map((s,i)=><li key={i}>{s}</li>)}</ol><p><strong>Could an incumbent absorb it?</strong> {product.incumbent_absorption_risk}</p></section>
   <h2 className="section-title">Customer pains this product connects</h2>
   {product.related_pain_ids.map(id=>{const p=report.pains.find(p=>p.id===id);return p?<section className="panel" key={id}><h3>{p.title}</h3><p>{p.problem}</p><p><strong>Consequence:</strong> {p.consequence}</p><p><strong>Current workaround:</strong> {p.workaround}</p><Refs ids={p.source_ids} report={report} demo={demo}/></section>:null;})}
  </>}
  <h2 className="section-title">Competitor and substitute landscape</h2>
  <p className="muted-text">Existing products show where budgets already exist. The question is why this buyer would choose a different product.</p>
  {o.competitors.length?<div className="competitor-table"><table><thead><tr><th>Alternative / customer</th><th>Price and adoption evidence</th><th>Switching costs and proposed opening</th></tr></thead><tbody>{o.competitors.map((c,i)=><tr key={i}><td><strong>{c.name}</strong><p><span className="pill">{c.category||"Not classified"}</span></p><p>{c.target_customer||"Target customer not assessed."}</p><p>{c.offering}</p></td><td><p>{c.price_evidence}</p><Refs ids={c.pricing_source_ids||[]} report={report} demo={demo}/><p>{c.adoption_evidence||"Adoption not independently established."}</p></td><td><p><strong>Switching:</strong> {c.switching_costs||"Not assessed."}</p><p><strong>Opening:</strong> {c.gap}</p><Refs ids={c.source_ids} report={report} demo={demo}/></td></tr>)}</tbody></table></div>:<section className="panel"><p>No sourced competitor comparison is available. This is a research gap, not proof of an empty market.</p></section>}
  {market?<><section className="panel market-case"><div className="gate-row"><h2>The market case</h2><span className={"pill "+(market.verdict==="supported"?"green":"amber")}>{market.verdict==="supported"?"Research-supported":market.verdict}</span></div><p><strong>Category:</strong> {market.category}</p><p><strong>Specific buyer segment:</strong> {market.target_segment}</p><p><strong>Reachable market:</strong> {market.reachable_market}</p><p><strong>Bottom-up estimate:</strong> {market.bottom_up_market_estimate||"Not assessed."}</p><p><strong>Assumptions:</strong> {(market.market_size_assumptions||[]).join(" ")||"None recorded."}</p><p><strong>Pricing logic:</strong> {market.pricing_logic}</p><p><strong>Differentiation:</strong> {market.differentiation}</p><p><strong>Why someone switches:</strong> {market.switching_trigger}</p><Refs ids={market.source_ids} report={report} demo={demo}/></section><section className="panel"><h3>Customer acquisition channels</h3>{(market.acquisition_channels||[]).length?(market.acquisition_channels||[]).map((c,i)=><div className="investigation-finding" key={i}><strong>{c.name}</strong><p>{c.target_role}: {c.evidence}</p><Refs ids={c.source_ids} report={report} demo={demo}/></div>):<p>No sourced path to the budget owner is established.</p>}</section><section className="panel"><h3>Demand and buying evidence</h3>{market.buying_signals.length?market.buying_signals.map((s,i)=><div className="investigation-finding" key={i}><span className="pill">{s.kind.replaceAll("_"," ")}</span><p>{s.claim}</p><Refs ids={s.source_ids} report={report} demo={demo}/></div>):<p>No supported demand signals yet.</p>}</section>{[["Competitor searches performed",market.competitor_search_notes],["Evidence against this market case",market.counterevidence],["Still needs customer validation",market.remaining_validation]].map(([title,items])=><section className="panel" key={title as string}><h3>{title as string}</h3><ul>{(items as string[]).map((s,i)=><li key={i}>{s}</li>)}</ul></section>)}</>:<section className="panel"><h3>Market not yet assessed</h3><p>Competitor names alone do not establish an addressable market or a reason to switch.</p></section>}
 </>;
}
