import {Search,Layers3,ShoppingBag,BarChart3,ShieldCheck,Eye,ArrowUpRight,ChevronRight,Link2} from "lucide-react";
import type {Report,Run,TrailItem} from "./types";

const stages:Record<string,[string,typeof Search,string]>={pain_discovery:["Customer pain",Search,"Signals become documented customer problems"],product_synthesis:["Product synthesis",Layers3,"Related pains become product hypotheses"],market_scan:["Competitors & market",ShoppingBag,"Products are checked against alternatives and demand"],assessment:["Assessment",BarChart3,"Evidence is translated into separate scores"],challenge:["Skeptical review",ShieldCheck,"The strongest claims are challenged"],evidence_gate:["Final gates",ShieldCheck,"The product and market case passes or stops"]};
const stageOrder=Object.keys(stages);
const label=(d:string)=>({found:"Found",advanced:"Advanced",merged:"Merged",watch:"Watch",rejected:"Rejected",insufficient_evidence:"Insufficient evidence",skipped:"Skipped"}[d]||d);
const negative=(decision:string)=>["rejected","insufficient_evidence"].includes(decision);
const unique=(items:string[])=>[...new Set(items)];

export function ResearchTrail({report,demo=false}:{report:Report;demo?:boolean}){
 const trail=report.research_trail||[];
 const groups=stageOrder.map(stage=>[stage,trail.filter(e=>e.stage===stage)] as const).filter(([,items])=>items.length);
 const names=new Map(trail.map(e=>[e.subject_id,e.title]));
 const usedBy=new Map<string,string[]>();
 trail.forEach(e=>e.related_ids.forEach(id=>usedBy.set(id,[...(usedBy.get(id)||[]),e.title])));
 return <details className="panel decision-trail"><summary><div><span className="eyebrow">OPTIONAL RESEARCH TRAIL</span><h2>See how Scout reached this result</h2><p>Open the evidence path, phase by phase.</p></div><span className="trail-open"><span className="pill">{trail.length} decisions</span><ChevronRight size={17}/></span></summary>{!trail.length?<p className="trail-empty">This historical report predates structured decision trails.</p>:<div className="trail-body"><div className="trail-map" aria-label="Research phases">{groups.map(([stage,items],i)=>{const [name,Icon]=stages[stage];const stopped=items.filter(e=>negative(e.decision)).length;return <div className="trail-map-step" key={stage}><span><Icon size={14}/></span><strong>{name}</strong><small>{items.length} decision{items.length===1?"":"s"}{stopped?` · ${stopped} stopped`:""}</small>{i<groups.length-1&&<ChevronRight size={14}/>}</div>;})}</div><div className="trail-phases">{groups.map(([stage,items])=><Phase key={stage} stage={stage} items={items} report={report} demo={demo} names={names} usedBy={usedBy}/>)}</div></div>}</details>;
}

function Phase({stage,items,report,demo,names,usedBy}:{stage:string;items:TrailItem[];report:Report;demo:boolean;names:Map<string,string>;usedBy:Map<string,string[]>}){
 const [name,Icon,description]=stages[stage]||[stage,Eye,""];
 const stopped=items.filter(e=>negative(e.decision)).length;
 return <details className="trail-phase" data-stage={stage}><summary><span className="trail-phase-icon"><Icon size={15}/></span><div><strong>{name}</strong><small>{description}</small></div><span className={"pill "+(stopped?"amber":"green")}>{stopped?`${stopped} stopped`:`${items.length} advanced`}</span><ChevronRight className="trail-chevron" size={16}/></summary><div className="trail-list">{items.map((e,i)=><Entry key={e.id+"-"+i} e={e} report={report} demo={demo} inputs={e.related_ids.map(id=>names.get(id)||id)} outputs={usedBy.get(e.subject_id)||[]}/>)}</div></details>;
}

function Entry({e,report,demo,inputs,outputs}:{e:TrailItem;report:Report;demo:boolean;inputs:string[];outputs:string[]}){
 return <article className={"trail-entry "+e.decision}><div className="trail-content"><div className="trail-head"><span className={"pill "+(negative(e.decision)?"amber":e.decision==="advanced"?"green":"")}>{label(e.decision)}</span><span>{e.subject_type.replaceAll("_"," ")}</span></div><h3>{e.title}</h3><p>{e.summary}</p>{(inputs.length>0||outputs.length>0)&&<div className="trail-links"><Link2 size={13}/><div>{inputs.length>0&&<p><strong>Built from:</strong> {unique(inputs).join(" · ")}</p>}{outputs.length>0&&<p><strong>Used by:</strong> {unique(outputs).join(" · ")}</p>}</div></div>}<div className="trail-details">{!!e.reasons.length&&<details><summary>Why this decision <span>{e.reasons.length}</span></summary><ul>{e.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul></details>}{!!e.source_ids.length&&<details><summary>Evidence used <span>{e.source_ids.length}</span></summary><div className="trail-sources">{e.source_ids.map(id=>{const src=report.sources.find(s=>s.id===id);return src?<a key={id} href={!demo&&/^https?:\/\//.test(src.url)?src.url:undefined} target="_blank" rel="noreferrer"><span>{id}</span>{src.title}<ArrowUpRight size={11}/></a>:null;})}</div></details>}{!!e.next_evidence.length&&<details><summary>What could advance or reopen this? <span>{e.next_evidence.length}</span></summary><ul>{e.next_evidence.map((n,i)=><li key={i}>{n}</li>)}</ul></details>}</div></div></article>;
}

export function LiveFindings({run}:{run:Run}){const cp=(run as any).checkpoints?.[String(run.revision)]||{},pains=cp.pain?.pains||[],products=cp.synthesis?.product_hypotheses||[],markets=cp.market_scan?.market_candidates||[],searches=cp.signals?.searches||[];if(!searches.length&&!pains.length&&!cp.synthesis&&!markets.length)return null;const coverage=[...new Set(searches.map((s:any)=>s.source).filter(Boolean))] as string[];return <details className="live-findings"><summary>Show findings collected so far</summary>{!!coverage.length&&<div><strong>Source coverage ({coverage.length})</strong><p><Eye size={12}/>{coverage.join(" · ")}<span>{searches.filter((s:any)=>s.error).length} unavailable queries recorded</span></p></div>}{!!pains.length&&<div><strong>Customer pains ({pains.length})</strong>{pains.map((p:any)=><p key={p.id}><Search size={12}/>{p.title}<span>{p.customer}</span></p>)}</div>}{cp.synthesis&&<div><strong>Product hypotheses ({products.length})</strong>{products.map((p:any)=><p key={p.name}><Layers3 size={12}/>{p.name}<span>{p.scope.replaceAll("_"," ")} · {p.segment_alignment||"alignment unknown"}</span></p>)}{!products.length&&<p>No coherent standalone product survived synthesis.</p>}</div>}{!!markets.length&&<div><strong>Markets checked ({markets.length})</strong>{markets.map((m:any)=><p key={m.product_name}><ShoppingBag size={12}/>{m.product_name}<span>{m.competitors.length} alternatives · {m.buying_signals.length} demand signals · {m.product_hunt_checks.length} Product Hunt products</span></p>)}</div>}</details>}
